#ifndef PACKET_PARSE_H
#define PACKET_PARSE_H
#include "record-types.h"

int packetParse_initEnv();
int packetParse_startup();

typedef enum {
    RECORD_PACKET_PARSE_OK = 0,
    RECORD_PACKET_PARSE_E_OPEN_FIFO,
    RECORD_PACKET_PARSE_E_BAD_PACKET,
    RECORD_PACKET_PARSE_E_NOT_IP_PACKET,
    RECORD_PACKET_PARSE_E_NOT_UDP_PACKET,
    RECORD_PACKET_PARSE_E_PUSH_SIP_QUEUE,
    RECORD_PACKET_PARSE_E_PUSH_RTP_QUEUE,
    RECORD_PACKET_PARSE_E_INIT_REDIS,
    RECORD_PACKET_PARSE_E_GENERAL
} PacketParseResult_t;

typedef enum {
    RECORD_SIP_MSG_HANDLE_RESULT_OK = 0,
    RECORD_SIP_MSG_HANDLE_RESULT_ALLOCATE_MEMORY_ERR   ,
    RECORD_SIP_MSG_HANDLE_RESULT_FORMAT_ERR            ,
    RECORD_SIP_MSG_HANDLE_RESULT_LACKOF_ESSENTIAL_FIELD,
    RECORD_SIP_MSG_HANDLE_RESULT_BED_VALUE             ,
    RECORD_SIP_MSG_HANDLE_RESULT_EMPTY_LIST            ,
    RECORD_SIP_MSG_HANDLE_RESULT_ELEMENT_NOT_EXIST     ,
    RECORD_SIP_MSG_HANDLE_RESULT_OPEN_FILE_ERROR       ,
} SIPMessageHandleResult_t;

#endif